http:
  port: 8081
network:
  name: base_sepolia
  httpRpcUrl: "https://sepolia.base.org"
  senderPrivateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  trustManagementRouterAddress: "0x400d925aCb3923c883671a48BA1d1C70D963E9F7"
  aavePoolAddress: "0x89c566D51E9483e86851e63538A588ec86725D2A"