http:
  port: 8081
network:
  name: mainnet
  httpRpcUrl: "https://ethereum-rpc.publicnode.com"
  senderPrivateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  trustManagementRouterAddress: "0x1234567890123456789012345678901234567890"
  teeWalletAddress: "0x1234567890123456789012345678901234567890"